### ISSUE TITLE
Settings page enhancements

### ISSUE THREAD

**Issue by fabiodrg** [msramalho/SigToCa#130]
Show some love to the options page. List of some ideas:
- [x] Present extractors with a more human-readable name. Add a nice icon as well.
- [ ] Similar to parameters, the storage options could have a human readable text, rather than an identifier name.
- [x] Remove the 'Reset all extractors' button. It is not implemented, as far as I know.
- [ ] Consider adding a "General" settings page that opens by default
  - [ ] Option to reset all extractors
  - [ ] Option to disable notification on new updates (#47)
  - [ ] Export/import settings
  - [ ] Resetting cache
  - [ ] ...
- [ ] Customisable order for the inputs in the options page. At the moment it will show textarea, text, checkboxes, .... If #100 is implemented, could use insertion order?
